import { Task } from './types';

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design Homepage Wireframe',
    description: 'Discuss layout with the marketing team for alignment on wireframes and typography pairing.',
    priority: 'low',
    dueDate: '2023-11-02',
    assignee: 'Devrizal Akbar',
    secondaryAssignees: ['Hanna Philips'],
    status: 'todo',
    tags: ['wireframe', 'homepage'],
    type: 'Feature',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-15T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-2',
    title: 'Audit Secure Key Management',
    description: 'Ensure hardware modules and cryptographic keys are correctly audited before testing.',
    priority: 'medium',
    dueDate: '2023-11-02',
    assignee: 'Davis Donin',
    secondaryAssignees: ['Talan Korsgaard', 'Hanna Philips'],
    status: 'todo',
    tags: ['security', 'cryptography'],
    type: 'Feature',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-20T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-3',
    title: 'Prepare Version 2.0 Docs',
    description: 'Draft the reference specifications and developer integration guidelines.',
    priority: 'low',
    dueDate: '2023-11-02',
    assignee: 'Devrizal Akbar',
    secondaryAssignees: ['Davis Donin'],
    status: 'todo',
    tags: ['docs', 'v2'],
    type: 'Feature',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-25T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-4',
    title: 'Final Quality Check Review',
    description: 'Complete cross-browser testing and device-density rendering checklists.',
    priority: 'high',
    dueDate: '2023-11-02',
    assignee: 'Talan Korsgaard',
    secondaryAssignees: [],
    status: 'todo',
    tags: ['qa', 'review'],
    type: 'Review',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-28T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-5',
    title: 'Develop Real-Time WebSocket Auth',
    description: 'Integrate the authentication handshake inside the live agent channel routing.',
    priority: 'high',
    dueDate: '2023-11-02',
    assignee: 'Davis Donin',
    secondaryAssignees: ['Talan Korsgaard'],
    status: 'in-progress',
    tags: ['auth', 'websockets'],
    type: 'Bug',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-15T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-6',
    title: 'Refactor Navigation Layout',
    description: 'Clean up spacing multipliers and update typography with unified Swiss Grotesk sizing.',
    priority: 'low',
    dueDate: '2023-11-02',
    assignee: 'Hanna Philips',
    secondaryAssignees: ['Devrizal Akbar'],
    status: 'in-progress',
    tags: ['ui', 'refactor'],
    type: 'Feature',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-22T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-7',
    title: 'Conduct Feedback Intercepts',
    description: 'Perform user testing of early prototypes and aggregate session recording comments.',
    priority: 'medium',
    dueDate: '2023-11-02',
    assignee: 'Talan Korsgaard',
    secondaryAssignees: ['Hanna Philips', 'Davis Donin'],
    status: 'in-progress',
    tags: ['testing', 'feedback'],
    type: 'Testing',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-24T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-8',
    title: 'Review System Integration Guidelines',
    description: 'Ensure correct client endpoints, caching intervals, and security schemas align fully.',
    priority: 'medium',
    dueDate: '2023-11-02',
    assignee: 'Devrizal Akbar',
    secondaryAssignees: ['Davis Donin'],
    status: 'in-progress',
    tags: ['integration', 'refactor'],
    type: 'Review',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-26T09:00:00Z',
    checked: false,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-9',
    title: 'Optimize Core Redis Caching',
    description: 'Enable sliding expiration rules and multi-node replication parameters for faster load.',
    priority: 'high',
    dueDate: '2023-11-02',
    assignee: 'Davis Donin',
    secondaryAssignees: ['Devrizal Akbar'],
    status: 'done',
    tags: ['database', 'redis'],
    type: 'Feature',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-15T09:00:00Z',
    checked: true,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-10',
    title: 'Upgrade API Key Rotation Security',
    description: 'Apply hash-based signatures and automated token refresh window filters secure.',
    priority: 'low',
    dueDate: '2023-11-02',
    assignee: 'Devrizal Akbar',
    secondaryAssignees: [],
    status: 'done',
    tags: ['security', 'keys'],
    type: 'Bug',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-21T09:00:00Z',
    checked: true,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  },
  {
    id: 'task-11',
    title: 'Deploy Production Gateway V1',
    description: 'Hook up cloud ingress route channels and warm up connection pools.',
    priority: 'medium',
    dueDate: '2023-11-02',
    assignee: 'Talan Korsgaard',
    secondaryAssignees: ['Davis Donin', 'Devrizal Akbar'],
    status: 'done',
    tags: ['devops', 'deployment'],
    type: 'Testing',
    timeline: '02 Nov 2023',
    createdAt: '2023-10-26T09:00:00Z',
    checked: true,
    commentsCount: 12,
    linksCount: 1,
    subtasksCompleted: 0,
    subtasksTotal: 3
  }
];
